### PR TITLE
Fix: Term element in content value gets parsed

### LINKED ISSUE #1387: Term 'element' in 'content' value gets parsed
Version: 10.2.3

If I use the word 'element' in a string value for 'content', the word will be prefixed.

```css
    content: "Element 'div' not allowed as child of element 'span' in this context.";
```

```css
  content: "Attribute width not allowed on -moz-element picture at this point.";
  content: "Attribute width not allowed on element picture at this point.";
```

The same output as input would be expected in this case.

```json
  "browserslist": [
    "> 2%",
    "last 2 years",
    "ie 11",
    "not ie_mob > 0",
    "not dead"
  ]
```

```
├── autoprefixer@10.2.3 
└─┬ stylelint@13.9.0
  └── autoprefixer@9.8.6 
```

### PR DESCRIPTION
**Pull request by lukewarlow**
Closes #1387

### CODE REVIEW

File: lib/processor.js [hunk 1]
```diff
@@ -497,6 +497,9 @@ class Processor {
         return true
       }
     }
+    if (node.type === 'decl' && node.prop === 'content') {
```
Comment (ai) [inline lib/processor.js:500]:
```suggestion
    if (node.prop === 'content') {
```

Only `Declaration` has `prop`.

File: test/autoprefixer.test.ts [hunk 2]
```diff
@@ -370,6 +381,9 @@ it('transition on vendor specific rule', () => {
 it('ignore prefix in vendor at rules', () => {
   check('at-rules')
 })
+it('ignore content property', () => {
+  check('content')
```
Comment (ai) [inline test/autoprefixer.test.ts:385]:
```suggestion
  let input = read('content')
  let result = postcss([prefixer('scope')]).process(input)
  expect(result.css).toEqual(input)
```

It will allow to avoid the same content in both files.

**Comment by ai** [comment]
Thanks. Released in 10.3.1.
